In [55]:
import plotly
import plotly.plotly as py
from plotly.graph_objs import *
import pandas as pd
import math

In [7]:
plotly.tools.set_credentials_file(username='lis590dv', api_key='0jCaIttf2QaVJ3lRZZlK')

In [41]:
df2 = pd.read_csv('t3sample.csv',encoding='iso-8859-1')
df2.head()

,names,dates,latitude,longitude,categorical,quant1,quant2,quant3
0,b'Rawad',1453008863,-19.988651,-41.435565,Category01,1.933239,6.052785,6105.123120
1,b'Eurma',1471778579,-8.593256,27.742604,Category00,1.520733,-11.065076,143.902725
2,b'Taleia',1473613446,-67.463164,-109.366796,Category04,1.863466,11.437340,2019.370225
3,b'Niley',1481194251,-7.537010,-32.218540,Category03,0.745431,19.415543,3225.920647
4,b'Acey',1454402794,-17.116866,2.949914,Category05,1.031100,17.714492,4976.099324

In [ ]:
df2

In [20]:
def WhaleTeam(dataset):
    df=pd.read_csv(dataset,encoding='iso-8859-1')
    colnames=df2.columns.values
    nameslen=len(colnames)
    nameslen=nameslen-5
    
    subplot(2,2,1)
    data = Data([
    Scattermapbox(
        lat=df['stop_lat'],
        lon=df['stop_lon'],
        mode='markers',
        marker=Marker(
            size=9,
            color='#cc99ff'
        ),
        text=df['stop_name'],
    )
    ])
    layout = Layout(
        autosize=True,
        hovermode='closest',
        mapbox=dict(
            accesstoken=mapbox_access_token,
            bearing=0,
            center=dict(
                lat=40.11,
                lon=-88.23
            ),
            pitch=0,
            zoom=10
        ),
    )
    
    fig = dict(data=data, layout=layout)
    py.iplot(fig, filename='Multiple Mapbox')

In [21]:
WhaleTeam('t3sample.csv')

       names       dates   latitude   longitude categorical    quant1  \
0   b'Rawad'  1453008863 -19.988651  -41.435565  Category01  1.933239
1   b'Eurma'  1471778579  -8.593256   27.742604  Category00  1.520733
2  b'Taleia'  1473613446 -67.463164 -109.366796  Category04  1.863466
3   b'Niley'  1481194251  -7.537010  -32.218540  Category03  0.745431
4    b'Acey'  1454402794 -17.116866    2.949914  Category05  1.031100

      quant2       quant3
0   6.052785  6105.123120
1 -11.065076   143.902725
2  11.437340  2019.370225
3  19.415543  3225.920647
4  17.714492  4976.099324

In [46]:
colnames=df2.columns.values

In [47]:
colnames

array(['names', 'dates', 'latitude', 'longitude', 'categorical', 'quant1',
       'quant2', 'quant3'], dtype=object)

In [82]:
nameslen=len(colnames)

In [83]:
nameslen=nameslen-5

In [84]:
nameslen

3

In [85]:
sqrt=math.sqrt(nameslen)

In [86]:
sqrt

1.7320508075688772

In [87]:
wd=math.trunc(sqrt)

In [88]:
lg=wd+1

In [89]:
lg

2

In [90]:
wd

1

In [91]:
if lg*wd<nameslen:
    wd=wd+1

In [94]:
wd

2

In [106]:
df2[colnames[4]]

0       Category01
1       Category00
2       Category04
3       Category03
4       Category05
5       Category00
6       Category04
7       Category04
8       Category07
9       Category09
10      Category01
11      Category01
12      Category05
13      Category08
14      Category09
15      Category02
16      Category09
17      Category00
18      Category02
19      Category09
20      Category09
21      Category05
22      Category09
23      Category08
24      Category09
25      Category07
26      Category00
27      Category06
28      Category02
29      Category07
           ...
9970    Category01
9971    Category02
9972    Category02
9973    Category08
9974    Category03
9975    Category03
9976    Category05
9977    Category03
9978    Category07
9979    Category02
9980    Category03
9981    Category02
9982    Category03
9983    Category05
9984    Category04
9985    Category05
9986    Category09
9987    Category00
9988    Category03
9989    Category00
9990    Category03
9991    Category06
9992    Category01
9993    Category02
9994    Category05
9995    Category05
9996    Category06
9997    Category00
9998    Category06
9999    Category09
Name: categorical, dtype: object

In [185]:
import plotly.plotly as py
from plotly.graph_objs import *
import pandas as pd

# read in volcano database data
#df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/volcano_db.csv')
df = pd.read_csv('t3sample.csv',encoding='iso-8859-1')
# frequency of Country
#freq = df
#freq = freq.Country.value_counts().reset_index().rename(columns={'index': 'x'})
freq=df[colnames[4]].value_counts().reset_index().rename(columns={'index': 'x'})
# plot(1) top 10 countries by total volcanoes
freqcol=freq.columns.values
locations = Bar(x=freq['x'][0:10],y=freq[freqcol[1]][0:10], marker=dict(color='#CF1020'))

# read in 3d volcano surface data
#df_v = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/volcano.csv')

# plot(2) 3d surface of volcano
#threed = Surface(z=df_v.values.tolist(), colorscale='Reds', showscale=False)
#logsizes=[]
#for i in range(len(df[colnames[4]])):
#    logsize=math.log10(float(df[colnames[5]][i]))
#    logsize=logsize*1.5
#    logsizes.append(logsize)

# plot(3)  scattergeo map of volcano locations
trace3 = {
  "geo": "geo3", 
  "lon": df[colnames[3]],
  "lat": df[colnames[2]],
  "hoverinfo": 'text',
  "marker": {
    "size": 5,
    "opacity": 0.8,
    "color": '#CF1020',
    "colorscale": 'Viridis'
  }, 
  "mode": "markers", 
  "type": "scattergeo"
}

data = Data([locations, trace3])

# control the subplot below using domain in 'geo', 'scene', and 'axis'
layout = {
  "plot_bgcolor": 'black',
  "paper_bgcolor": 'black',
  "titlefont": {
      "size": 20,
      "family": "Raleway"
  },
  "font": {
      "color": 'white'
  },
  "dragmode": "zoom", 
  "geo3": {
    "domain": {
      "x": [0, 0.55], 
      "y": [0, 0.9]
    }, 
    "lakecolor": "rgba(127,205,255,1)",
    "oceancolor": "rgb(6,66,115)",
    "landcolor": 'white',
    "projection": {"type": "orthographic"}, 
    "scope": "world", 
    "showlakes": True,
    "showocean": True,
    "showland": True,
    "bgcolor": 'black'
  }, 
  "margin": {
    "r": 10, 
    "t": 25, 
    "b": 40, 
    "l": 60
  }, 
  "scene": {"domain": {
      "x": [0.5, 1], 
      "y": [0, 0.55]
    },
           "xaxis": {"gridcolor": 'white'},
           "yaxis": {"gridcolor": 'white'},
           "zaxis": {"gridcolor": 'white'}
           }, 
  "showlegend": False, 
  "title": "<br>Volcano Database", 
  "xaxis": {
    "anchor": "y", 
    "domain": [0.6, 0.95]
  }, 
  "yaxis": {
    "anchor": "x", 
    "domain": [0.1, 0.9],
    "showgrid": False
  }
}

annotations = { "text": "Histrogram of %s" % colnames[5],
               "showarrow": False,
               "xref": "paper",
               "yref": "paper",
               "x": 0.85,
               "y": 0.95}

layout['annotations'] = [annotations]

fig = Figure(data=data, layout=layout)
py.iplot(fig, filename = "Mixed Subplots Volcano")

In [111]:
freq

                                    x  Country
0                       United States      184
1                              Russia      169
2                           Indonesia      136
3                               Japan      111
4                               Chile       87
5                            Ethiopia       57
6                    Papua New Guinea       54
7                         Philippines       49
8                              Mexico       41
9                             Iceland       38
10                         Antarctica       35
11                            Ecuador       34
12                          Argentina       34
13                      Pacific Ocean       33
14                        New Zealand       30
15                              Kenya       22
16                        El Salvador       22
17                          Guatemala       22
18                             Canada       21
19                              Tonga       20
20                          Nicaragua       19
21                               Peru       16
22                            Vanuatu       14
23                              China       14
24                              Italy       14
25                           Portugal       14
26                           Colombia       14
27                             Turkey       13
28                     Atlantic Ocean       12
29                            Bolivia       11
..                                ...      ...
66                             Panama        2
67                        South Korea        2
68                              India        2
69                       Arctic Ocean        2
70                              Samoa        2
71  French Southern & Antarctic Lands        2
72                          Bouvet I.        1
73            Heard I. & McDonald Is.        1
74                  St. Kitts & Nevis        1
75                             Sweden        1
76                         Martinique        1
77                     United Kingdom        1
78                         Guadeloupe        1
79                            Germany        1
80                          Jan Mayen        1
81                            Reunion        1
82                          Australia        1
83                             Rwanda        1
84                     American Samoa        1
85                         Montserrat        1
86                            Grenada        1
87                           Malaysia        1
88                               Mali        1
89                    Wallis & Futuna        1
90                       South Africa        1
91                          St. Lucia        1
92                            Nigeria        1
93                Sao Tome & Principe        1
94       St. Vincent & the Grenadines        1
95                           Trinidad        1

[96 rows x 2 columns]

In [115]:
#freq = freq.Country.value_counts().reset_index().rename(columns={'index': 'x'})

df2freq=df2[colnames[4]].value_counts().reset_index().rename(columns={'index': 'x'})

In [117]:
df2freq

            x  categorical
0  Category04         1077
1  Category05         1038
2  Category03         1033
3  Category02         1024
4  Category07         1016
5  Category06          998
6  Category01          972
7  Category08          955
8  Category00          954
9  Category09          933

In [126]:
freqcol=df2freq.columns.values
df2freq[freqcol[1]][0:10]

0    1077
1    1038
2    1033
3    1024
4    1016
5     998
6     972
7     955
8     954
9     933
Name: categorical, dtype: int64

In [124]:
freqcol=df2freq.columns.values

In [125]:
freqcol[1]

'categorical'

In [168]:
import plotly.plotly as py
from plotly.graph_objs import *
import pandas as pd

# read in volcano database data
#df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/volcano_db.csv')
df = pd.read_csv('DiscGrants96to13-2017_04_10_19_27_08.csv',encoding='iso-8859-1',sep='\t')
# frequency of Country
#freq = df
#freq = freq.Country.value_counts().reset_index().rename(columns={'index': 'x'})
freq=df['InstState'].value_counts().reset_index().rename(columns={'index': 'x'})
# plot(1) top 10 countries by total volcanoes
freqcol=freq.columns.values
locations = Bar(x=freq['x'][0:10],y=freq[freqcol[1]][0:10], marker=dict(color='#CF1020'))

# read in 3d volcano surface data
df_v = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/volcano.csv')

# plot(2) 3d surface of volcano
threed = Surface(z=df_v.values.tolist(), colorscale='Reds', showscale=False)
#threed = Bar(x=freq['x'][0:10],y=freq[freqcol[1]][0:10], marker=dict(color='#CF1020'))


# plot(3)  scattergeo map of volcano locations
trace3 = {
  "geo": "geo3", 
  "lon": df['Longitude'],
  "lat": df['Latitude'],
  "hoverinfo": 'text',
  "marker": {
    "symbol":"circle",
    "size": logsizes,
    "opacity": 0.05,
    "color": '#FF9999',
    "colorscale": 'Viridis'
    #"line": {
    #    "width":0,
    #},
  }, 
  "mode": "markers", 
  "type": "scattergeo"
}

data = Data([locations, trace3])

# control the subplot below using domain in 'geo', 'scene', and 'axis'
layout = {
  "plot_bgcolor": 'black',
  "paper_bgcolor": 'black',
  "titlefont": {
      "size": 20,
      "family": "Raleway"
  },
  "font": {
      "color": 'white'
  },
  "dragmode": "zoom", 
  "geo3": {
    "domain": {
      "x": [0, 0.55], 
      "y": [0, 0.9]
    }, 
    "lakecolor": "rgba(127,205,255,1)",
    "oceancolor": "rgb(6,66,115)",
    "landcolor": 'white',
    "projection": {"type": "orthographic"}, 
    "scope": "world", 
    "showlakes": True,
    "showocean": True,
    "showland": True,
    "bgcolor": 'black'
  }, 
  "margin": {
    "r": 10, 
    "t": 25, 
    "b": 40, 
    "l": 60
  }, 
  "scene": {"domain": {
      "x": [0.5, 1], 
      "y": [0, 0.55]
    },
           "xaxis": {"gridcolor": 'white'},
           "yaxis": {"gridcolor": 'white'},
           "zaxis": {"gridcolor": 'white'}
           }, 
  "showlegend": False, 
  "title": "<br>Volcano Database", 
  "xaxis": {
    "anchor": "y", 
    "domain": [0.6, 0.95]
  }, 
  "yaxis": {
    "anchor": "x", 
    "domain": [0, 0.95],
    "showgrid": False
  }
}

annotations = { "text": "Source: NOAA",
               "showarrow": False,
               "xref": "paper",
               "yref": "paper",
               "x": 0,
               "y": 0}

layout['annotations'] = [annotations]

fig = Figure(data=data, layout=layout)
py.iplot(fig, filename = "Mixed Subplots Volcano")

In [151]:
logsizes=[]
for i in range(len(df['AwardTotal'])):
    logsize=math.log10(df['AwardTotal'][i])
    logsize=logsize*1.5
    logsizes.append(logsize)

In [141]:
logsizes

[3.530199698203082,
 3.780317312140151,
 3.780317312140151,
 3.8027737252919755,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.8027737252919755,
 3.791690649020118,
 3.5415792439465807,
 3.780317312140151,
 3.7686381012476144,
 3.7686381012476144,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.530199698203082,
 3.530199698203082,
 3.791690649020118,
 3.791690649020118,
 3.791690649020118,
 3.780317312140151,
 3.5185139398778875,
 3.780317312140151,
 3.780317312140151,
 3.7686381012476144,
 3.5185139398778875,
 3.8027737252919755,
 3.7686381012476144,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.8027737252919755,
 3.8027737252919755,
 3.780317312140151,
 3.7686381012476144,
 3.780317312140151,
 3.791690649020118,
 3.530199698203082,
 3.780317312140151,
 3.5415792439465807,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.7686381012476144,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.7686381012476144,
 3.780317312140151,
 3.530199698203082,
 3.780317312140151,
 3.530199698203082,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.791690649020118,
 3.8027737252919755,
 3.530199698203082,
 3.530199698203082,
 3.7686381012476144,
 3.7686381012476144,
 3.7686381012476144,
 3.780317312140151,
 3.791690649020118,
 3.780317312140151,
 3.780317312140151,
 3.5415792439465807,
 3.7686381012476144,
 3.530199698203082,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.791690649020118,
 3.5415792439465807,
 3.8027737252919755,
 3.8027737252919755,
 3.780317312140151,
 3.7686381012476144,
 3.780317312140151,
 3.5185139398778875,
 3.8027737252919755,
 3.8027737252919755,
 3.530199698203082,
 3.780317312140151,
 3.791690649020118,
 3.7686381012476144,
 3.780317312140151,
 3.530199698203082,
 3.791690649020118,
 3.5185139398778875,
 3.5185139398778875,
 3.780317312140151,
 3.5415792439465807,
 3.780317312140151,
 3.791690649020118,
 3.8027737252919755,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.7686381012476144,
 3.780317312140151,
 3.530199698203082,
 3.791690649020118,
 3.5185139398778875,
 3.5185139398778875,
 3.530199698203082,
 3.7686381012476144,
 3.780317312140151,
 3.5415792439465807,
 3.530199698203082,
 3.530199698203082,
 3.780317312140151,
 3.530199698203082,
 3.8027737252919755,
 3.780317312140151,
 3.791690649020118,
 3.780317312140151,
 3.780317312140151,
 3.791690649020118,
 3.780317312140151,
 3.780317312140151,
 3.5514499979728753,
 3.791690649020118,
 3.791690649020118,
 3.7686381012476144,
 3.780317312140151,
 3.780317312140151,
 3.791690649020118,
 3.791690649020118,
 3.791690649020118,
 3.791690649020118,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.7686381012476144,
 3.791690649020118,
 3.780317312140151,
 3.530199698203082,
 3.7686381012476144,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.780317312140151,
 3.8027737252919755,
 3.8041394323353503,
 3.5717088318086874,
 3.561101383649056,
 3.8041394323353503,
 3.561101383649056,
 3.8041394323353503,
 3.8041394323353503,
 3.5717088318086874,
 3.814913181275074,
 3.561101383649056,
 3.5717088318086874,
 3.814913181275074,
 3.8041394323353503,
 3.8254261177678233,
 3.79309160017658,
 3.561101383649056,
 3.8041394323353503,
 3.5717088318086874,
 3.814913181275074,
 3.5717088318086874,
 3.79309160017658,
 3.8041394323353503,
 3.79309160017658,
 3.8041394323353503,
 3.79309160017658,
 3.814913181275074,
 3.582063362911709,
 3.8041394323353503,
 3.8041394323353503,
 3.79309160017658,
 3.79309160017658,
 3.8041394323353503,
 3.79309160017658,
 3.5717088318086874,
 3.8041394323353503,
 3.814913181275074,
 3.5717088318086874,
 3.8254261177678233,
 3.8041394323353503,
 3.79309160017658,
 3.5717088318086874,
 3.5717088318086874,
 3.8041394323353503,
 3.8041394323353503,
 3.814913181275074,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.5717088318086874,
 3.79309160017658,
 3.8041394323353503,
 3.582063362911709,
 3.5717088318086874,
 3.582063362911709,
 3.5717088318086874,
 3.8254261177678233,
 3.8041394323353503,
 3.5717088318086874,
 3.8041394323353503,
 3.8041394323353503,
 3.5717088318086874,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.5717088318086874,
 3.561101383649056,
 3.79309160017658,
 3.8041394323353503,
 3.561101383649056,
 3.8041394323353503,
 3.8041394323353503,
 3.79309160017658,
 3.8041394323353503,
 3.5717088318086874,
 3.8041394323353503,
 3.5717088318086874,
 3.5717088318086874,
 3.8254261177678233,
 3.8254261177678233,
 3.8254261177678233,
 3.814913181275074,
 3.561101383649056,
 3.5717088318086874,
 3.814913181275074,
 3.8041394323353503,
 3.8254261177678233,
 3.814913181275074,
 3.814913181275074,
 3.5921767573958667,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8254261177678233,
 3.79309160017658,
 3.5717088318086874,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.582063362911709,
 3.8041394323353503,
 3.8041394323353503,
 3.8254261177678233,
 3.814913181275074,
 3.8041394323353503,
 3.814913181275074,
 3.8254261177678233,
 3.8041394323353503,
 3.8254261177678233,
 3.5717088318086874,
 3.561101383649056,
 3.5717088318086874,
 3.814913181275074,
 3.8041394323353503,
 3.5717088318086874,
 3.582063362911709,
 3.561101383649056,
 3.814913181275074,
 3.814913181275074,
 3.814913181275074,
 3.79309160017658,
 3.8041394323353503,
 3.79309160017658,
 3.8254261177678233,
 3.8041394323353503,
 3.8041394323353503,
 3.5717088318086874,
 3.8041394323353503,
 3.582063362911709,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.79309160017658,
 3.814913181275074,
 3.8254261177678233,
 3.582063362911709,
 3.582063362911709,
 3.5717088318086874,
 3.79309160017658,
 3.8041394323353503,
 3.8041394323353503,
 3.582063362911709,
 3.8041394323353503,
 3.79309160017658,
 3.8041394323353503,
 3.5717088318086874,
 3.5717088318086874,
 3.8041394323353503,
 3.79309160017658,
 3.8041394323353503,
 3.8041394323353503,
 3.79309160017658,
 3.79309160017658,
 3.561101383649056,
 3.561101383649056,
 3.814913181275074,
 3.8041394323353503,
 3.8041394323353503,
 3.5921767573958667,
 3.8041394323353503,
 3.5717088318086874,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.5717088318086874,
 3.5717088318086874,
 3.8041394323353503,
 3.561101383649056,
 3.8041394323353503,
 3.79309160017658,
 3.8254261177678233,
 3.814913181275074,
 3.582063362911709,
 3.561101383649056,
 3.8041394323353503,
 3.5717088318086874,
 3.8041394323353503,
 3.814913181275074,
 3.8254261177678233,
 3.8041394323353503,
 3.8041394323353503,
 3.5717088318086874,
 3.8041394323353503,
 3.814913181275074,
 3.8041394323353503,
 3.814913181275074,
 3.561101383649056,
 3.582063362911709,
 3.79309160017658,
 3.8041394323353503,
 3.8254261177678233,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.582063362911709,
 3.5717088318086874,
 3.8041394323353503,
 3.8041394323353503,
 3.8254261177678233,
 3.5717088318086874,
 3.79309160017658,
 3.8041394323353503,
 3.79309160017658,
 3.8041394323353503,
 3.5717088318086874,
 3.8041394323353503,
 3.8041394323353503,
 3.5717088318086874,
 3.5717088318086874,
 3.5921767573958667,
 3.8041394323353503,
 3.8254261177678233,
 3.814913181275074,
 3.8041394323353503,
 3.8254261177678233,
 3.5717088318086874,
 3.8041394323353503,
 3.79309160017658,
 3.8254261177678233,
 3.8041394323353503,
 3.814913181275074,
 3.5717088318086874,
 3.5717088318086874,
 3.8254261177678233,
 3.79309160017658,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.8041394323353503,
 3.814913181275074,
 3.814913181275074,
 3.8041394323353503,
 3.5717088318086874,
 3.5717088318086874,
 3.8041394323353503,
 3.561101383649056,
 3.814913181275074,
 3.5717088318086874,
 3.5717088318086874,
 3.79309160017658,
 3.582063362911709,
 3.814913181275074,
 3.8041394323353503,
 3.814913181275074,
 3.8041394323353503,
 3.814913181275074,
 3.814913181275074,
 3.561101383649056,
 3.8041394323353503,
 3.561101383649056,
 3.8041394323353503,
 3.79309160017658,
 3.79309160017658,
 3.814913181275074,
 3.814913181275074,
 3.8041394323353503,
 3.8041394323353503,
 3.8254261177678233,
 3.79309160017658,
 3.582063362911709,
 3.8254261177678233,
 3.561101383649056,
 3.8041394323353503,
 3.8041394323353503,
 3.79309160017658,
 3.5717088318086874,
 3.814913181275074,
 3.79309160017658,
 3.79309160017658,
 3.814913181275074,
 3.5717088318086874,
 3.8041394323353503,
 3.561101383649056,
 3.8041394323353503,
 3.814913181275074,
 3.561101383649056,
 3.8041394323353503,
 3.582063362911709,
 3.814913181275074,
 3.814913181275074,
 3.8790958795000727,
 3.89707700320942,
 3.888179493918325,
 3.8790958795000727,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.888179493918325,
 3.888179493918325,
 3.89707700320942,
 3.888179493918325,
 3.8790958795000727,
 3.89707700320942,
 3.663700925389648,
 3.8790958795000727,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.888179493918325,
 3.655138434811382,
 3.655138434811382,
 3.888179493918325,
 3.663700925389648,
 3.89707700320942,
 3.888179493918325,
 3.888179493918325,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.8790958795000727,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.663700925389648,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.8790958795000727,
 3.663700925389648,
 3.655138434811382,
 3.888179493918325,
 3.89707700320942,
 3.663700925389648,
 3.888179493918325,
 3.655138434811382,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.6464037262230695,
 3.888179493918325,
 3.888179493918325,
 3.888179493918325,
 3.888179493918325,
 3.888179493918325,
 3.8790958795000727,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.8790958795000727,
 3.8790958795000727,
 3.663700925389648,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.888179493918325,
 3.8790958795000727,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.8790958795000727,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.663700925389648,
 3.89707700320942,
 3.655138434811382,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.6464037262230695,
 3.663700925389648,
 3.89707700320942,
 3.888179493918325,
 3.888179493918325,
 3.888179493918325,
 3.89707700320942,
 3.8790958795000727,
 3.89707700320942,
 3.6464037262230695,
 3.888179493918325,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.663700925389648,
 3.888179493918325,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.89707700320942,
 3.655138434811382,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.888179493918325,
 3.663700925389648,
 3.89707700320942,
 3.655138434811382,
 3.89707700320942,
 3.655138434811382,
 3.888179493918325,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.663700925389648,
 3.888179493918325,
 3.888179493918325,
 3.89707700320942,
 3.888179493918325,
 3.655138434811382,
 3.89707700320942,
 3.89707700320942,
 3.8790958795000727,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.663700925389648,
 3.663700925389648,
 3.89707700320942,
 3.655138434811382,
 3.655138434811382,
 3.663700925389648,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.655138434811382,
 3.663700925389648,
 3.663700925389648,
 3.8790958795000727,
 3.663700925389648,
 3.8790958795000727,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.6464037262230695,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.663700925389648,
 3.663700925389648,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.6464037262230695,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.888179493918325,
 3.663700925389648,
 3.89707700320942,
 3.655138434811382,
 3.89707700320942,
 3.89707700320942,
 3.6464037262230695,
 3.888179493918325,
 3.888179493918325,
 3.655138434811382,
 3.6464037262230695,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.89707700320942,
 3.8790958795000727,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.663700925389648,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.89707700320942,
 3.655138434811382,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.655138434811382,
 3.89707700320942,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.89707700320942,
 3.655138434811382,
 3.89707700320942,
 3.89707700320942,
 3.655138434811382,
 3.888179493918325,
 3.6464037262230695,
 3.89707700320942,
 3.8790958795000727,
 3.89707700320942,
 3.6464037262230695,
 3.89707700320942,
 3.8790958795000727,
 3.663700925389648,
 3.8790958795000727,
 3.89707700320942,
 3.8790958795000727,
 3.8790958795000727,
 3.655138434811382,
 3.6464037262230695,
 3.663700925389648,
 3.655138434811382,
 3.888179493918325,
 3.663700925389648,
 3.8790958795000727,
 3.89707700320942,
 3.8790958795000727,
 3.663700925389648,
 3.6464037262230695,
 3.89707700320942,
 3.89707700320942,
 3.655138434811382,
 3.888179493918325,
 3.663700925389648,
 3.655138434811382,
 3.655138434811382,
 3.89707700320942,
 3.8790958795000727,
 3.663700925389648,
 3.89707700320942,
 3.663700925389648,
 3.663700925389648,
 3.89707700320942,
 3.6464037262230695,
 3.8790958795000727,
 3.89707700320942,
 3.888179493918325,
 3.89707700320942,
 3.663700925389648,
 3.888179493918325,
 3.89707700320942,
 3.655138434811382,
 3.888179493918325,
 3.8790958795000727,
 3.8790958795000727,
 3.89707700320942,
 3.89707700320942,
 5.90687353472207,
 6.2040931098534715,
 6.2057455409426625,
 3.8135809885681917,
 3.786041210242554,
 3.513217600067939,
 3.8135809885681917,
 3.756636108245848,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.756636108245848,
 3.8135809885681917,
 3.786041210242554,
 3.756636108245848,
 3.786041210242554,
 3.786041210242554,
 3.8135809885681917,
 3.756636108245848,
 3.786041210242554,
 3.8135809885681917,
 3.756636108245848,
 3.786041210242554,
 3.8135809885681917,
 3.513217600067939,
 3.786041210242554,
 3.756636108245848,
 3.513217600067939,
 3.513217600067939,
 3.756636108245848,
 3.8135809885681917,
 3.5634810853944106,
 3.786041210242554,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.786041210242554,
 3.8135809885681917,
 3.756636108245848,
 3.8135809885681917,
 3.756636108245848,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.786041210242554,
 3.756636108245848,
 3.5634810853944106,
 3.5634810853944106,
 3.8135809885681917,
 3.8135809885681917,
 3.756636108245848,
 3.8135809885681917,
 3.5634810853944106,
 3.8135809885681917,
 3.756636108245848,
 3.8135809885681917,
 3.756636108245848,
 3.786041210242554,
 3.5634810853944106,
 3.786041210242554,
 3.8135809885681917,
 3.786041210242554,
 3.756636108245848,
 3.786041210242554,
 3.5634810853944106,
 3.756636108245848,
 3.756636108245848,
 3.8135809885681917,
 3.786041210242554,
 3.5634810853944106,
 3.8135809885681917,
 3.513217600067939,
 3.786041210242554,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.786041210242554,
 3.756636108245848,
 3.756636108245848,
 3.8135809885681917,
 3.5634810853944106,
 3.8135809885681917,
 3.513217600067939,
 3.756636108245848,
 3.786041210242554,
 3.786041210242554,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.786041210242554,
 3.5634810853944106,
 3.8135809885681917,
 3.8135809885681917,
 3.5634810853944106,
 3.8135809885681917,
 3.8135809885681917,
 3.756636108245848,
 3.786041210242554,
 3.8135809885681917,
 3.756636108245848,
 3.8135809885681917,
 3.5634810853944106,
 3.8135809885681917,
 3.756636108245848,
 3.756636108245848,
 3.8135809885681917,
 3.8135809885681917,
 3.786041210242554,
 3.8135809885681917,
 3.5634810853944106,
 3.8135809885681917,
 3.756636108245848,
 3.8135809885681917,
 3.786041210242554,
 3.786041210242554,
 3.756636108245848,
 3.8135809885681917,
 3.5634810853944106,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.786041210242554,
 3.8135809885681917,
 3.8135809885681917,
 3.8135809885681917,
 3.5185139398778875,
 3.7528164311882715,
 3.780317312140151,
 3.7641761323903307,
 3.7234556720351857,
 3.7528164311882715,
 3.780317312140151,
 3.780317312140151,
 3.530199698203082,
 3.530199698203082,
 3.7528164311882715,
 3.780317312140151,
 3.530199698203082,
 3.7234556720351857,
 3.711807229041191,
 3.780317312140151,
 3.780317312140151,
 3.7234556720351857,
 3.780317312140151,
 3.7234556720351857,
 3.734799829588847,
 3.4800069429571505,
 3.7686381012476144,
 3.780317312140151,
 3.780317312140151,
 3.741151598851785,
 3.7528164311882715,
 3.741151598851785,
 3.530199698203082,
 3.780317312140151,
 3.780317312140151,
 3.5185139398778875,
 3.7234556720351857,
 3.5415792439465807,
 3.7528164311882715,
 3.5185139398778875,
 3.530199698203082,
 3.7528164311882715,
 3.5185139398778875,
 3.7234556720351857,
 3.780317312140151,
 3.780317312140151,
 3.7528164311882715,
 3.780317312140151,
 3.530199698203082,
 3.780317312140151,
 3.7686381012476144,
 3.4683473304121573,
 3.5185139398778875,
 3.780317312140151,
 3.5415792439465807,
 3.780317312140151,
 3.734799829588847,
 3.7234556720351857,
 3.530199698203082,
 3.7641761323903307,
 3.791690649020118,
 3.530199698203082,
 3.4800069429571505,
 3.780317312140151,
 3.780317312140151,
 3.734799829588847,
 3.7234556720351857,
 3.745855195173729,
 3.7686381012476144,
 3.745855195173729,
 3.530199698203082,
 3.734799829588847,
 3.780317312140151,
 3.5415792439465807,

In [137]:
df['AwardTotal']

0          3390.0
1          6030.0
2          6030.0
3          6350.0
4          6030.0
5          6030.0
6          6030.0
7          6350.0
8          6190.0
9          3480.0
10         6030.0
11         5870.0
12         5870.0
13         6030.0
14         6030.0
15         6030.0
16         3390.0
17         3390.0
18         6190.0
19         6190.0
20         6190.0
21         6030.0
22         3300.0
23         6030.0
24         6030.0
25         5870.0
26         3300.0
27         6350.0
28         5870.0
29         6030.0
           ...
13170     57197.0
13171    131000.0
13172    823016.0
13173    139762.0
13174    328329.0
13175     59100.0
13176    149983.0
13177    129000.0
13178    249837.0
13179    150000.0
13180    499710.0
13181    148150.0
13182    149996.0
13183    212367.0
13184    239443.0
13185    222623.0
13186     98908.0
13187    166500.0
13188    135000.0
13189    505826.0
13190    150000.0
13191    883171.0
13192    646720.0
13193    141500.0
13194    150000.0
13195    140341.0
13196     52329.0
13197    673344.0
13198    150000.0
13199     64594.0
Name: AwardTotal, dtype: float64